In [2]:
from mxnet import nd
import random

#  初始化卷积核
#  卷积核满足的分布函数
def myfunction(x):
    return x

def kernel(kernel_size, MyFunction):
    kernel_grid = nd.zeros(shape=kernel_size)
    for i in range(kernel_grid.shape[0]):
        for j in range(kernel_grid.shape[1]):
            kernel_grid[i][j] = MyFunction(random.randint(1,10))
    return kernel_grid
def Conv():
    pass

In [3]:
kernel((3,3), myfunction)


[[ 2.  7.  3.]
 [10.  2.  4.]
 [ 3.  2.  4.]]
<NDArray 3x3 @cpu(0)>