In [1]:
import numpy as np
from mxnet import nd

In [20]:
x = np.array(np.arange(16),ndmin=4)
x

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15]]]])

In [19]:
type(x)  # 由此可见array是一个函数名,ndarray是一个类型。矩阵类型。单行或单列矩阵叫向量。

numpy.ndarray

In [10]:
y = nd.ones(shape=(5,3))
y


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 5x3 @cpu(0)>