In [1]:
from mxnet import nd
from mxnet.gluon import nn


In [3]:
"""
读写NDArray.直接使用save, load函数
"""
x = nd.ones(3)
nd.save('x', x)  # 将x存入名为x的文件中

In [4]:
x2 = nd.load('x')  # 将文件x的数据读取到x2中
x2

[
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>]

In [5]:
y = nd.zeros(4)
nd.save('xy', [x, y])  # 将x,y存入xy中
x2, y2 = nd.load('xy')  # 加载到x2, y2中
(x2, y2)

(
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>)

In [6]:
"""
存储并读取一个从字符串映射到NDArray的字典
"""
mydict = {'x':x,'y':y}
nd.save('mydict',mydict)
mydict2 = nd.load('mydict')
mydict2


{'x': 
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 'y': 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>}

In [7]:
"""
读写Gluon模型的参数
"""
class MLP(nn.Block):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Dense(256, activation='relu')
        self.output = nn.Dense(10)

    def forward(self, x):
        return self.output(self.hidden(x))

net = MLP()
net.initialize()
x = nd.random.uniform(shape=(2, 20))
y = net(x)
filename = 'mlp.params'
net.save_parameters(filename)

In [8]:
net2 = MLP()
net2.load_parameters(filename)

In [9]:
y2 = net2(x)
y2 == y


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 2x10 @cpu(0)>